services:
  app:
    build:
      context: .
      dockerfile: ./app/app.containerfile
    ports:
      - "8501:8501"

  model_inference_endpoint:
    build:
      context: .
      dockerfile: ./model-inference-endpoint/inference.containerfile
    volumes:
      - ../data:/usr/src/app/data
    ports:
      - "8000:8000"
